Правки и упрощение структуры отчёта
spbu-se/matmex-diploma-template pull request #20
Opened 2024-01-13 20:26 UTC by yurii-litvinov

- Убраны экзотические разделы (которых я ни разу не видел в работах кафедры), "Метод" переименован в "Описание решения", рекомендации из "implementation" переехали сюда же, Threats to Validity переехали в "Эксперимент"
- Отступы четырьмя пробелами (табуляции для отступов нынче не в моде)
- Соответственно отступы поменялись везде, причём в том же коммите, что и содержательные изменения, но уж как получилось
- У нас теперь нет годовых и полугодовых практик, у нас есть непрерывная работа, за которую раз в полгода надо отчитываться, так что убраны все "к Новому году" — можно начать весной и закончить осенью
- Англоязычный титульник теперь можно не комментировать, он сам не генерится, когда не нужен
- Добавлено несколько, как кажется, важных рекомендаций, хотя есть Методичка и Чеклист по оформлению репозиториев
- Поправлено много опечаток
- Проверено под Windows, дополнен и допереведён README
- По умолчанию рекомендуем minted, потому что он круче

2024-01-14 18:29 UTC, WoWaster requested changes
За текст спасибо — он классный и многое поясняет, по крайней мере студенту. Minted давно хотелось сделать стандартом, боюсь только мы огребем, когда у людей шаблон из коробки собираться не станет по весне :)

2024-01-14 18:29 UTC, WoWaster commented on 040_experiment.tex
> +\end{itemize}
Может здесь лучше `description` вместо `itemize`?

2024-01-14 18:29 UTC, WoWaster commented on 050_conclusion.tex
> +\textbf{Обязательно.} Список результатов, который будет либо один к одному соответствовать задачам из раздела~\ref{sec:task}, либо их уточнять (например, если было <<выбрать>>, то тут <<выбрано то-то
Ёлочки остались :(

2024-01-14 18:29 UTC, WoWaster commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Про format поспорю. latexindent хочет видеть Perl в системе. Кажется последний раз я решал это установкой [Strawberry Perl](https://strawberryperl.com/). @yurii-litvinov, если Вы опробуете у себя — будет круто

2024-01-14 18:29 UTC, WoWaster commented on matmex-diploma-custom.cls
>  \usemintedstyle{bw}
Только у нас стиль включен черно-белый. Если сейчас работы особо не печатают, то может быть стоит включить что-нибудь другое

2024-01-14 18:29 UTC, WoWaster commented on matmex-diploma-custom.cls
> +% Запретим minted подсвечивать по его мнению лексические ошибки
А можно пример, когда он это делает?

2024-01-14 18:29 UTC, WoWaster commented on matmex-diploma-custom.cls
>  \newcommand\maketitleru{
В этом макросе у нас куча << и >>, я думаю можно гвоздями прибить csquotes и сделать всё совсем единообразно

2024-01-14 18:29 UTC, WoWaster commented on matmex-diploma-custom.cls
> +\sloppy
LaTeX Stack Exchange считает `\sloppy` плохой практикой 
* https://tex.stackexchange.com/questions/241343/what-is-the-meaning-of-fussy-sloppy-emergencystretch-tolerance-hbadness
* https://tex.stackexchange.com/questions/409809/best-practice-always-use-fussy-for-drafts-and-sloppy-for-finals

2024-01-14 18:29 UTC, WoWaster commented on 030_solution.tex
> +Реализация в широком смысле: что таки было сделано. Часто это нна самом деле несколько отдельных разделов, по одному на каждую \enquote{реализационную} задачу из постановки. Например, \enquote{Архите
```suggestion
Реализация в широком смысле: что таки было сделано. Часто это на самом деле несколько отдельных разделов, по одному на каждую \enquote{реализационную} задачу из постановки. Например, \enquote{Архитектура} и \enquote{Особенности реализации}, либо по разделу на каждую крупную подзадачу. Если разделы получились недостаточно эпичными (меньше пары страниц), сделайте их подразделами одного большого раздела, как тут.
```

2024-01-14 18:29 UTC, WoWaster commented on README.md
> +* Рекомендовано @Kakadu и @yurii-litvinov: поставить дистрибутив TeX на desktop (например, [TeXLive](https://www.tug.org/texlive))
Я бы сказал не «например», а «строго TeX Live или MacTeX», а то потом вылезают проблемы со всякими любителями MikTeX да на Linux

2024-01-14 18:29 UTC, WoWaster commented on README.md
> +* Рекомендовано @Kakadu и @yurii-litvinov: поставить дистрибутив TeX на desktop (например, [TeXLive](https://www.tug.org/texlive))
Боюсь, что надо куда-то написать чего требуется «доставить» в общем случае, чтобы всё работало как часы. Как минимум я знаю про Perl под Windows для latexindent и про pygments для minted

2024-01-14 18:29 UTC, WoWaster commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Вместо xelatex оптимальнее будет вызвать latexmk как это и описано в Makefile

2024-01-14 18:29 UTC, WoWaster commented on README.md
> +* Файл `ugost2008ls.bst` был взят [отсюда](https://github.com/anlun/Russian-Phd-LaTeX-Dissertation-Template/tree/master/BibTeX-Styles), потому что оригинальный из пакета `texlive-lang-cyrillic` даёт
TODO нам с @Kakadu: а нужен ли этот файл в 2024 году?

2024-01-15 08:52 UTC, gsvgit commented on 030_solution.tex
> +    \item неразрывные пробелы там, где нужны пробелы, но переносить на другую строку нельзя, например \verb=т.~е.= или \verb=А.~Н.~Терехов=;
Ещё один важный пример это 
```
smthng~\cite{!!!}
smthng~\ref{!!!}
```

2024-01-15 08:52 UTC, gsvgit commented on 030_solution.tex
> +Это бывает полезно в текстах, а ещё чаще~--- в презентациях. Пример сделан на основе вопроса на \textsc{StackOveflow}\footnote{\url{https://tex.stackexchange.com/questions/284311} (дата доступа: \DTM
Сопровождающий текст в сносках должен быть. Иначе решат, что так можно, и будем получать портянки ссылко без пояснения, что и как.

2024-01-15 08:52 UTC, gsvgit commented on 040_experiment.tex
> +\subsection{Результаты}
Где-то тут ссылка на методичку Кирилла Константиновича.

2024-01-15 08:52 UTC, gsvgit commented on 030_solution.tex
> +Учебные практики и ВКР отличаются тем, что тут есть требования отдельных глав (слайдов) со списком задач и списком результатов. Но даже если Вы забьёте на требования, специфичные для ВКР, и соблюдете
Я бф куда-то сюда добавил примеры хороших работ студентов. От сбея могу порекомендовать магистерскую Егора Орачёва. И текст вполне, и репозиторий оформлен, и результаты ок.

2024-01-15 09:11 UTC, yurii-litvinov commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
latexmk как раз хочет Perl, так что "вручную" — это как раз крайняя мера, когда ничего не работает. Ну, правда, minted требует Python, так что не заработает всё равно :)

На Windows у меня заработало прямо как есть, ничего доустанавливать было не надо, Perl специально для этого не ставил, и вообще не помню, чтобы ставил когда-то. Вполне возможно, его TeXLive с собой таскает, там много чего на Perl.

2024-01-15 09:14 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
>  \usemintedstyle{bw}
Да, думаю можно вернуть стиль по умолчанию, но как коллеги решат.

2024-01-15 09:17 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
> +% Запретим minted подсвечивать по его мнению лексические ошибки
Я это у себя вроде везде изжил, поэтому не покажу, но если посреди листинга, например, многоточие вставить, он вокруг него жёлтую рамочку нарисует без этой команды.

2024-01-15 09:19 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
> +\sloppy
Всё так. Но без этого в каждой второй работе текст иногда выезжает не то что на поля, а за границу листа. Никто с переводами вручную не заморачивается. Так что предлагаю оставить, или правильно настроить штрафы в стилевом файле, но это я сам толком не умею.

2024-01-15 09:22 UTC, yurii-litvinov commented on 040_experiment.tex
> +\subsection{Результаты}
Знать бы эту ссылку

2024-01-15 10:00 UTC, WoWaster commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Latexmk завёлся, а latexindent нет? Или я чего-то не понимаю?

2024-01-15 10:06 UTC, WoWaster commented on matmex-diploma-custom.cls
> +\sloppy
Я бы по умолчанию оставил без `\sloppy`, если уж учить делать хорошо, то сразу же. Кажется это всё-таки не так сложно фиксить слова на полях. 

Есть ещё вариант пересесть целиком на lualatex, там полноценно работает microtype и многих проблем нет. Я у себя лично видел слова на полях только из-за формул и иногда из-за `\texttt`.

Если уж очень хочется иметь «простое» решение для текста на полях, то лучше перенести `\sloppy` в `preamble.tex`, закомментировать и обвешать предупреждениями, что лучше не надо, но если вы по-другому не можете, то уж ладно, включите.

2024-01-15 10:07 UTC, WoWaster commented on 040_experiment.tex
> +\subsection{Результаты}
Я думаю речь об этой ссылке: https://github.com/spbu-se/measurements

2024-01-15 10:22 UTC, yurii-litvinov commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Не, дело не в latexindent. Цель format написана очень линуксово, например, find не на каждой Windows есть (хотя и велики шансы, что есть, git тащит с собой целый Cygwin вроде, и даже прописывает это в пути, если попросить).

2024-01-15 12:54 UTC, Kakadu commented on 030_solution.tex
> +\subsubsection{Выделения куска листинга с помощью tikz}
Я не помню. Вроде находили, но мне придется искать заново

2024-01-15 15:33 UTC, yurii-litvinov commented on README.md
> +* Рекомендовано @Kakadu и @yurii-litvinov: поставить дистрибутив TeX на desktop (например, [TeXLive](https://www.tug.org/texlive))
А вот бы кто докер-образ собрал, сразу со всем барахлом, которое нужно.

2024-01-15 15:34 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
>  \usemintedstyle{bw}
Вернул по умолчанию

2024-01-15 15:36 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
> +\sloppy
Основная беда --- это \url, оно по недосмотру вылезает на поля только так. А как всё-таки хорошо, явно указывать переносы? Кажется, что это а) должна делать polyglossia, и б) это крайне смущает спеллчекер.

2024-01-15 15:45 UTC, Kakadu commented on README.md
> +* Файл `ugost2008ls.bst` был взят [отсюда](https://github.com/anlun/Russian-Phd-LaTeX-Dissertation-Template/tree/master/BibTeX-Styles), потому что оригинальный из пакета `texlive-lang-cyrillic` даёт
Ошибка осталась

2024-01-15 15:50 UTC, Kakadu commented on matmex-diploma-custom.cls
> +\sloppy
Я предлагаю пока без sloppy, и отложить это на другой PR. Чем он так плох, я пока не читал.

2024-01-15 15:56 UTC, Kakadu commented on 040_experiment.tex
> +\subsection{Результаты}
сделал

2024-01-15 15:59 UTC, Kakadu commented on README.md
> +* Рекомендовано @Kakadu и @yurii-litvinov: поставить дистрибутив TeX на desktop (например, [TeXLive](https://www.tug.org/texlive))
Давайте помержим это не делая докер-образ

2024-01-15 16:10 UTC, Kakadu commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
https://github.com/spbu-se/matmex-diploma-template/pull/20/commits/f2023f8822079bdc1e54f0263b03c48644fd0b4d
Вроде пофиксил. @WoWaster

2024-01-15 16:36 UTC, WoWaster commented on 030_solution.tex
> +\subsubsection{Выделения куска листинга с помощью tikz}
https://tex.stackexchange.com/questions/298383/how-to-highlight-color-draw-attention-to-a-particular-snippet-in-minted 
Судя по всему есть два подхода к тому как красить, но в любом случае надо проверить, может будет вырвиглазно смотреться

2024-01-15 16:37 UTC, WoWaster commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Круто. @yurii-litvinov, можете проверить раз уж только у Вас в наличии винда с техом?

2024-01-15 16:48 UTC, WoWaster commented on matmex-diploma-custom.cls
> +\sloppy
>  А как всё-таки хорошо, явно указывать переносы?

Либо ad-hoc решение через `\-` в нужном месте, либо где-то в прембуле завести список всех слов с нетривиальными переносами:
> TEX provides the command \hyphenation{⟨exceptions⟩} to globally define hyphenation exceptions which override the hyphenation patterns for specified
words. The command takes as argument a space-separated list of words where
hyphenation points are marked by a dash (if no dash is used, the respective word
is not hyphenated at all):
> ```latex 
> \hyphenation{%
> po-ly-glos-sia
> LaTeX
> }
> ```
[Дока к polyglossia](https://mirror.truenetwork.ru/CTAN/macros/unicodetex/latex/polyglossia/polyglossia.pdf), страница 16

2024-01-15 17:50 UTC, WoWaster commented on 030_solution.tex
> +В этом случае закомментируйте всё, что связано с minted, в matmex-diploma-custom.cls.
«И ни в коем случае не смешивайте эти пакеты в одном документе!»
Что-то такое явно стоит написать

2024-01-18 07:58 UTC, yurii-litvinov commented on README.md
> +- под Windows `mingw32-make` или `nmake` тоже справятся, но цели format, depext и depext-deb работать не будут (то есть, вызывать `mingw32-make depext` нет смысла). Можно собирать вручную командой `x
Проверил, не работает (генерит командную строку с пачкой вызовов latexindent через точку с запятой и завершается с ошибкой 3, что бы это ни значило). Разбираться не хочу, потому что в .vscode/settings.json всё ок, в VS Code работает идеально, а не в VS Code нечего теховские документы и писать :) Подозреваю, что Windows + локальный TeX + не VS Code — это столь редкий случай использования, что может не встретиться никогда.

2024-01-18 08:00 UTC, yurii-litvinov commented on matmex-diploma-custom.cls
> +\sloppy
А поправьте тогда шаблон, чтобы был xurl и пример ручной расстановки переносов.

2024-01-18 08:01 UTC, yurii-litvinov commented on 030_solution.tex
> +Учебные практики и ВКР отличаются тем, что тут есть требования отдельных глав (слайдов) со списком задач и списком результатов. Но даже если Вы забьёте на требования, специфичные для ВКР, и соблюдете
Магистерская не выложена :) Но добавил пример одного из бойцов Анастасии Корниловой, там тоже всё по канону.

2024-01-18 08:03 UTC, Kakadu commented on matmex-diploma-custom.cls
> +\sloppy
https://github.com/spbu-se/matmex-diploma-template/issues/21

2024-01-18 08:04 UTC, Kakadu commented on README.md
> +* Файл `ugost2008ls.bst` был взят [отсюда](https://github.com/anlun/Russian-Phd-LaTeX-Dissertation-Template/tree/master/BibTeX-Styles), потому что оригинальный из пакета `texlive-lang-cyrillic` даёт
https://github.com/spbu-se/matmex-diploma-template/issues/22

2024-01-18 08:10 UTC, Kakadu commented on 030_solution.tex
> +\subsubsection{Выделения куска листинга с помощью tikz}
https://github.com/spbu-se/matmex-diploma-template/issues/24

2024-01-18 08:17 UTC, Kakadu commented on 030_solution.tex
> +          \footnote{Это не шутка, в хороших работах, где целый семестр делался только обзор, оно примерно так и выходит.},
Кто-то может подумать, что для хорошей работы надо делать целый семестр обзор...

2024-01-18 08:20 UTC, Kakadu commented on 030_solution.tex
> +    \item если нет, то, наверное, обзор получился годным и ценным сам по себе, источников 40-50 было рассмотрено%
```suggestion
    \item если нет, то, наверное, обзор получился годным и ценным сам по себе, источников 40--50 было рассмотрено%
```

2024-01-18 13:32 UTC, gsvgit commented on 030_solution.tex
> +Учебные практики и ВКР отличаются тем, что тут есть требования отдельных глав (слайдов) со списком задач и списком результатов. Но даже если Вы забьёте на требования, специфичные для ВКР, и соблюдете
Ну как так! Выкладываем всякое, а топовые работы не выкладываем.

2024-01-20 19:44 UTC, WoWaster commented on 030_solution.tex
> +          Не посылайте текст даже научному руководителю на проверку, если не прогнали спеллчекер, желательно, умеющий проверять пунктуацию --- у научника куча времени уйдёт на комментарии вида \enquo
Можно ~~рекламу~~ упоминание такого спеллчекера? Я сходу только Word знаю, но конвертить pandoc'ом TeX в Word как-то жоско звучит
P.S. Кажется в этом коммите везде забыт неразрывный пробел перед тире :)

2024-02-02 06:33 UTC, merged